name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'master'
      - 'releases/v*'
    tags:
      - 'v*'
  pull_request:
    paths-ignore:
      - '.github/mage-releases.json'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # TODO: uncomment when arm64 binaries are available: https://github.com/magefile/mage/issues/481
          # - macos-15
          # - macos-14
          - macos-13
          - windows-latest
        version:
          - latest
          - v1.8.0
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          cache-dependency-path: test/go.sum
      -
        name: Mage
        uses: ./
        with:
          version: ${{ matrix.version }}
          args: build
          workdir: test
          cache-binary: false

  install-only:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # TODO: uncomment when arm64 binaries are available: https://github.com/magefile/mage/issues/481
          # - macos-15
          # - macos-14
          - macos-13
          - windows-latest
        version:
          - latest
          - v1.8.0
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install Mage
        uses: ./
        with:
          version: ${{ matrix.version }}
          install-only: true
          cache-binary: false
      -
        name: Show Mage version
        run: mage --version

  cache-binary:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install Mage
        uses: ./
        with:
          version: v1.14.0
          install-only: true
          cache-binary: true
      -
        name: Show Mage version
        run: mage --version
